version: '2'
services:
  users_db:
    image: mysql:5.7
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: users
      MYSQL_HOST: users_db
  users_ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3396 -b '0.0.0.0'"
    ports:
      - "3396:3396"
    depends_on:
      - users_db
